### ISSUE TITLE
Drafting Proposals: A lot of projects felt reluctant to submit proposals, and may be running into issues. Add drafting so users can resume.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#109]
### Problem:
A lot of users are either reluctant to write proposals, or may also experience issues along the way that cause them to fail, or want to return to complete their proposal.

## Towards a solution:
Save the projects & proposals forms in local storage via svelte => storage.
This could be abstracted from users, so they can return and complete at any time.

## Design:
There are different ways to tackling this problem. 
1. Users could save this information and have the objects created, so they can resume.
2. Information is saved in the background/form, so when users return to it, it's prefilled with there they left off.

**Comment by trentmc** [comment]
$ requested >> $ available, so we don't have an issue with supply of proposals

Therefore this issue is super low priority, closing
