### ISSUE TITLE
[Staging][Bug] - If a proposal wasn't funded. I can't create another one.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#154]
### Problem: Project is blocked:
- Project admin can't create another proposal
- Project admin is unable to complete previous proposal/deliverable

Project: https://test-portal.oceandao.org/project/6258f5c75936d305f907ae87
- Last proposal was round 20
- Proposal didn't receive any funding on that round

**Comment by KatunaNorbert** [comment]
Are you sure it is related to previous proposal not be funded, I was looking into code but haven't seen check on that when creating proposal. 
I also had a not funded previous proposal and was able to create another one.
Could you provide some info about the error you are receiving?

**Comment by trizin** [comment]
#159 fixed
