### ISSUE TITLE
Browser / Wallet Integration in Seed Website

### ISSUE THREAD

**Issue by rbb36** [oceanprotocol/oceandao-proposal-portal#16]
**Describe the bug**
The new Seed website appears to require a wallet app integrated into the browser.

**To Reproduce**
1. Install a browser without an integrated wallet app.
2. Go to https://seed.oceandao.org/
3. Click on 'Connect Wallet'
4. Click on 'Connect Wallet' Again
5. Click on 'Connect Wallet' feverishly, like a ferret or other small, hyperactive rodent.
6. See nothing happen.
7. Open Browser Tools > Web Developer Tools (or similar)
8. Refresh the browser.
9. Observe the following error:

<Router> Could not find an element to focus. You should always render a header for accessibility reasons, or set a custom focus element via the "useFocus" hook. If you don't want this Route or Router to manage focus, pass "primary={false}" to it.

Occurred in: <Route path="/" /> warning.js:54:9
Uncaught (in promise) TypeError: window.ethereum is undefined
    bl ethers.js:13
    Rc App.svelte:14
    ft index.mjs:1862
    <anonymous> main.js:4
    app main.js:4
    <anonymous> quill.js:9
ethers.js:13:29
    bl ethers.js:21
    Rc App.svelte:14
    ft index.mjs:1862
    <anonymous> main.js:4
    app main.js:4
    <anonymous> quill.js:9

**Expected behavior**
It would be nice if the new website would work for people who choose not to integrate their wallets with their browsers, to reduce the risk of issues like [data leakage](https://en.wikipedia.org/wiki/MetaMask#Criticism). That would permit old fussy people like me to continue developing new features for Ocean Protocol.

**Screenshots**
I have one, will try to attach after submitting, don't see a way to include it inline right now.

Failed to find an easy way to upload a screenshot. I'm fairly confident this is not hard to reproduce.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Tested in Firefox and Chromium, details from Firefox.
 - Version: 97.0.1

**Additional context**

**Comment by trizin** [comment]
Hi! Thanks for bringing this up. We plan to add support for different wallet apps, including "Walletconnect" in the near future.

**Comment by idiom-bytes** [comment]
Deployed to staging + production.
