### ISSUE TITLE
Update canCreateProposal in BE

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#161]
### Problem:
Right now, the project/proposal route to check if one can be created, can be improved.

`canCreateProposals` means we should check every condition that is required to return a simple true/false.
`receivedFundingAndNotReported` is what's developed at the moment.

(2) is a subset of (1)

### DoD:
- [x] receivedFundingAndNotReported has been implemented as canCreateProposals

### Deferred to separate issue:
- [x] Lay out some plans to implement testing inside of portal

**Comment by trizin** [comment]
#177
Checks if the proposal is funded and **not** completed.
