### ISSUE TITLE
Earmark Options Don't Match My Current Status

### ISSUE THREAD

**Issue by rbb36** [oceanprotocol/oceandao-proposal-portal#162]
**Describe the bug**
The "What earmark are you applying to?" dropdown offers me "New Entrants" and "Core Tech". We (DeadmanDAO / Web3HackerNetwork) won a "New Entrants" grant in R16, have submitted our deliverables, and they have been approved. I would like to apply for the "2nd/3rd Timers" category.

**To Reproduce**
1. Go to https://seed.oceandao.org/
2. Connect Wallet
3. View Project
4. View R17 Proposal
5. Update Proposal
6. Earmark shows as blank (see screenshot "initially-empty-earmark.png")
7. Click earmark dropdown
8. See "New Entrants" and "Core Tech" options in dropdown (see screenshot "populated-dropdown.png")

**Expected behavior**
The dropdown should offer the "2nd/3rd Timers" earmark option.

**Screenshots**
![initially-empty-earmark](https://user-images.githubusercontent.com/2435883/166107881-2b9637d5-caa8-43d7-8036-40f170a5c009.png)

![populated-dropdown](https://user-images.githubusercontent.com/2435883/166107882-61a426e0-a84f-4d34-a02e-7caa028e5896.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 99.0.1

**Additional context**
Travelling, should be able to add more detail by mid-day Sunday if needed. DeadmanBob#7342 on Discord.

Thank you!

**Comment by trizin** [comment]
Thanks for reporting this issue.
This commit should fix it: 502d8cc6af211932a1cfe96bb7ce02eab748abb2

Please let me know if the issue persists.
