### ISSUE TITLE
Improve proposal create/update functionality

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#20]
/proposal/update/ not working
- [x] Should be able to submit proposals until deadline
- [x] Should be able to update proposals until voting begins
- [x] Update Proposal Page UX so it's contextual to funding round mechanisms. Proposals can only submit deliverables after receiving the "Funded" state
- [x] Other users also reported "Updated Proposal" functionality as not working.
https://discord.com/channels/612953348487905282/776848812534398986/948340278811566131

**Comment by trizin** [comment]
https://discord.com/channels/612953348487905282/776848812534398986/948340278811566131
137afc2b2349687215e54daa3738e7de8115340a should fix

**Comment by idiom-bytes** [comment]
Let's review this during DD & after voting ends. 
- Update proposal should only enable certain fields to be changed.
- Grey out/disable fields and components that become immutable.

### DoD:
- [ ] Proposal cannot be modified unintended. Only certain stages of the Funding Round should enable edits.

**Comment by trizin** [comment]
> Timothy was able to create two different projects, one with a trailing name.
> 
> * There was a potential issue in tracking requests, where the request array was not cleared and users were therefore blocked from making follow-up requests.

https://github.com/oceanprotocol/oceandao-proposal-portal/pull/76
https://github.com/oceanprotocol/oceandao-proposal-portal/pull/73
