### ISSUE TITLE
Project Category + Proposal Earmark + Discourse Handle are not shared in Discourse post

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#22]
When a proposal is submitted to discord, there are missing fields:
- Project Category
- Proposal Earmark
- Discourse Handle
- Amount Requested
- Minimum Amount Requested

**Comment by OceanWally** [comment]
Can sm1 post a screenie of how this looks as a post in Discord rn? thxxx 🙏 @idiom-bytes @trizin

Or was "Discord" a typo, re: Discourse?

**Comment by trizin** [comment]
This is a typo; "When a proposal is submitted to ~discord~ **discourse**, there are missing fields:" @OceanWally

**Comment by malvonme** [comment]
Thx @trizin 🙏

**Comment by idiom-bytes** [comment]
There might be other improvements we can do with regards to restructuring/shuffling the proposal so that each line item is better laid out.

https://github.com/oceanprotocol/oceandao/issues/187

Please consider this update as part of this cleanup.

**Comment by malvonme** [comment]
Hey everyone, 

I gave this some thought, before and now again. 

We have 2 main goals here IMO:
A) Max. time-efficient proposal consumption
B) Max. navigation-efficient / consistent proposal consumption

Hence, I am proposing the following order:

Project Name
Discourse Handle
Project Category
Proposal Earmark 
Proposal One-Liner 
Proposal Description
 Project Description
Final Product
 Grant Deliverables 
Value Add Criteria
Core Team 
Advisors
Amount Requested
Minimum Amount Requested

This has some thought behind, as in: 

**I) Grasp all proposal basics in 30 seconds (DYOR on 30+ projects), focus A):**
Project Name
Discourse Handle
Project Category
Proposal Earmark 
Proposal One-Liner 
Proposal Description

**II) Keep on reading, deeper DYOR, what is the strategy, angles, final product, focus B):**
Project Description
Final Product 
Grant Deliverables
 Value Add Criteria

**III) Hard specs, who are the people behind, what do they request (USD)?** Quickly scroll to the bottom to check III), feeding into A) and B):
Core Team 
Advisors
Amount Requested
Minimum Amount Requested

CC:
@idiom-bytes @trizin

**Comment by malvonme** [comment]
After syncing with @trizin, there are 2 minor updates to that list (will repost here):

1. We do not have a Discourse Handle at the moment, as PORTAL often vanilla-creates a new discourse account for the proposer now. Take out. (Main target here was to be able to personally TAG the proposer for better signalling of updates/questions)

Action point:
Re-assess, make it a new ticket/feature, or leave out for now. @idiom-bytes 

2. Proposal Title is currently in the Discourse Title. This makes readers actually miss the proposal title (/hard to disambiguate from project title also). Let's put it into the main text instead. 

*Added wording recommendation for writing a proposal in portal. Devs, please us / do not use at own discretion. Goal here is to be able to understand the difference between proposal and project title, description, etc. If you feel is self-explanatory, keep as is.

**### New List of items:** 

Project Name
Project Category
Proposal Earmark 
_Proposal Title_ [-> optional for authors in portal: Give your proposal a catchy title (e.g. your main goal)]
Proposal One-Liner  [-> optional for authors in portal: Summarize your proposal in one catchy line or sentence(e.g. your main goal)]
Proposal Description
Project Description
Final Product
Grant Deliverables 
Value Add Criteria
Core Team 
Advisors
Amount Requested
Minimum Amount Requested

**Comment by malvonme** [comment]
CC @KatunaNorbert re:portal

**Comment by malvonme** [comment]
PS:
This also means that we are taking the PROPOSAL TITLE out of the discourse document/page TITLE, which will make it cleaner and faster to grasp.
