### ISSUE TITLE
Implement admin/create/

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#34]
// route.add("/admin/create/") onlyOwner

Signer.findOneAndUpdate(
  {
    address: "your address",
  },
  { $set: { privilege: 5 } },
  (err, data) => console.log(err, data)
);

**Comment by idiom-bytes** [comment]
-- Admin Portal
Should we consider adding the following?
- View - Admin List => Address + securityLevel 
- admin/remove/

**Comment by trizin** [comment]
Not sure what do you mean by `View - Admin List => Address + securityLevel`
`/admin/create` endpoint can set privilege to any number, `/admin/remove` is not necessary
