### ISSUE TITLE
Submit Deliverables UX - User should not be able to submit deliverables until "Funded" state

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#61]
### Problem:
Currently, projects are able to submit deliverables as soon as the proposal is created. This also causes issues because users can complete the proposal before voting starts.

### DoD:
- [x] Users should not be able to do it until proposal is under "Funded" state
- [x] Users should not be able to submit deliverables in other bad states either.

**Comment by trizin** [comment]
#53
