### ISSUE TITLE
Min Funding Requested not displayed on proposal after creation

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/oceandao-proposal-portal#71]
After I created a new proposal and accessed the update proposal page the min funding requested value it's 0.
![Screenshot 2022-03-31 at 10.18.14.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/a3f1b4b2-aebd-4ac6-9d52-8b5a4f1093bd)![Screenshot 2022-03-31 at 10.21.03.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/fcc33330-ae34-4671-82d5-06fe0a286c58)

**Comment by trizin** [comment]
Fixed on latest
