### ISSUE TITLE
Admin Discourse Response: Everything is bold. Update format to perhaps be more flexible & use md/html

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao-proposal-portal#87]
### Problem:
When I use the admin portal and accept/reject deliverables, the [response to port is completely bolded](https://port.oceanprotocol.com/t/maintain-ocean-protocol-core-component-documentation/940/16) and impacts any formatting I might have done.

## DoD:
- [ ] I can use the admin portal, provide a response using a rich-text field, and have that feedback propagated on Discourse.

**Comment by malvonme** [comment]
Line breaks would also be great, in composing field and in display in port.
